[functions]
  directory = "."
  external_node_modules = ["express", "serverless-http", "cors", "dotenv", "fs"]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true
